language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
matrix:
  include:
  - os: linux
    dist: xenial
    go: 1.13.x
    env:
      - lint
    git:
      submodules: false
    script:
    - pwd
    - ls -lshart
    - go run build/ci.go lint
