language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
jobs:
  include:

  # Run linter check. Only test code linters on latest version of Go.
  - stage: lint
    os: linux
    dist: xenial
    go: 1.15.x
    env:
      - lint
    git:
      submodules: false
    script:
      - make lint

  # Run build and tests on ARM64 on Pull Requests.
  - stage: build
    name: "ARM64/Go1.15.x: make test"
    os: linux
    arch: arm64
    dist: xenial
    go: 1.15.x
    env:
      - GO111MODULE=on
    script:
      - go run build/ci.go install -dlgo
      - travis_wait 60 go run build/ci.go test $TEST_PACKAGES
