name: ARM Tests

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Test ARM
    runs-on: ubuntu-18.04
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        id: go
        with:
          go-version: ^1.16

      - uses: actions/checkout@v2.1.0
        with:
          submodules: 'recursive'

      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run Tests
        id: runtests
        with:
          arch: armv6
          distro: ubuntu18.04
          install: |
            curl -O https://golang.org/dl/go1.16.linux-armv6l.tar.gz
            tar -C /usr/local -xzf go1.16.linux-armv6l.tar.gz
            export PATH=$PATH:/usr/local/go/bin
            go version

          run: |
            go run build/ci.go test -coverage ./...
