name: Benchmark

on:
  push:
    branches: [ bench ]
  pull_request:
    branches: [ bench ]

jobs:

  build:
    name: Bench
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Git remotes
        run: |
          git remote add upstream https://github.com/ethereum/go-ethereum.git
          git fetch upstream

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          date --iso-8601=hours | sed 's/:/_/g' > DATEFILE
          mkdir -p ./build/bench-results
          sudo apt-get -y install bc

      - name: Bench core-geth
        run: |
          git rev-parse HEAD | cut -c1-10 > COREGETH_HEAD
          go test -timeout=5m -bench=. -run='^$' -count=5 ./... | tee ./build/bench-results/core-geth-$(cat DATEFILE)-$(cat COREGETH_HEAD).out

      - name: Bench go-ethereum
        run: |
          git checkout upstream/master
          git rev-parse HEAD | cut -c1-10 > GOETHEREUM_HEAD
          go test -timeout=5m -bench=. -run='^$' -count=5 ./... | tee ./build/bench-results/go-ethereum-$(cat DATEFILE)-$(cat GOETHEREUM_HEAD).out
          git checkout bench

      - name: Benchstat
        run: |
          go get golang.org/x/perf/cmd/benchstat
          benchstat ./build/bench-results/go-ethereum-$(cat DATEFILE)-$(cat GOETHEREUM_HEAD).out ./build/bench-results/core-geth-$(cat DATEFILE)-$(cat COREGETH_HEAD).out | tee ./build/bench-results/stat-$(cat DATEFILE)-$(cat GOETHEREUM_HEAD)-$(cat COREGETH_HEAD).txt
          ./build/filter-stat.sh ./build/bench-results/stat-$(cat DATEFILE)-$(cat GOETHEREUM_HEAD)-$(cat COREGETH_HEAD).txt

      - name: Commit results
        run: |
          git add ./build/bench-results
          git config --local user.email "b5c6@protonmail.com"
          git config --local user.name "meows"
          git commit -m "Benchmarking results $(cat DATEFILE)\n\ngo-ethereum=$(cat GOETHEREUM_HEAD)\ncore-geth=$(cat COREGETH_HEAD)\ngithub-run-id=${GITHUB_RUN_ID}\ngithub-run-number=${GITHUB_RUN_NUMBER}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: bench

      - uses: actions/upload-artifact@v2
        with:
          name: bench-results-$(cat DATEFILE)-$(GOETHEREUM_HEAD)-$(cat COREGETH_HEAD)
          path: ./build/bench-results/
